apiVersion: v1
# mengatur jenis objek yaitu Service
kind: Service
# mengatur metadata / informasi terkait objek yang akan dibuat
metadata:
  name: mongodb
  labels:
    app: mongodb
# mengatur spesifikasi objek yang akan dibuat seperti port, dll
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017