apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: karsajobs
        image: anandailyasa/karsajobs:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 20m
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongodb
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: MONGO_ROOT_PASSWORD