apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
        containers:
        - name: karsajobs-ui
          image: anandailyasa/karsajobs-ui:latest
          ports:
          - containerPort: 8000
